### ISSUE TITLE
auto update error (missing yml file)

### ISSUE THREAD

**Issue by jabooth** [menpo/landmarker-app#10]
I'm seeing this error every time I change the asset folder:

<img width="937" alt="screenshot 2017-05-24 08 45 17" src="https://cloud.githubusercontent.com/assets/1312873/26412372/684ebfda-405d-11e7-8b6c-c722c25df5ae.png">

guess we need to commit this yml file?

**Comment by gabrielcowley** [comment]
Apparently `autoUpdate` should not be expected to work for non-packaged applications (ie development mode). I will add a more foolproof check for development mode using `electron-is-dev` which is the recommended tool.

**Comment by gabrielcowley** [comment]
Fix has now been pushed.
