### ISSUE TITLE
Landmarker app not working, landmarker.io website down

### ISSUE THREAD

**Issue by ndabby** [menpo/landmarker-app#15]
The app seems to be trying to connect to an online server. The program stalls for several minutes and when I quite the application I get the following error message:

<img width="420" alt="Landmarker-error_message" src="https://user-images.githubusercontent.com/5759299/57395644-7dfb9080-717d-11e9-8732-e27d374e26c6.png">

**Comment by jabooth** [comment]
- www.landmarker.io should now be back up again (although allow for DNS propagation).
- I wouldn't recommend using this old electron app variant - it hasn't been maintained. I'll update the readme to make that clear.
